import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { createWebsitesModule } from '../../../src/application/websites/websites-module.js';
import { WebsitesClientRepository } from '../../../src/infrastructure/repositories/websites-client-repository.js';
import { WebsitesProjectRepository } from '../../../src/infrastructure/repositories/websites-project-repository.js';
import { IncomeProfileRepository } from '../../../src/infrastructure/repositories/income-profile-repository.js';
import { InMemoryStorageAdapter } from '../../../src/infrastructure/storage/memory-storage-adapter.js';
import { ApplicationTransaction } from '../../../src/infrastructure/storage/application-transaction.js';
import { WebsitesPaymentRepository } from '../../../src/infrastructure/repositories/websites-payment-repository.js';
import { AccountRepository } from '../../../src/infrastructure/repositories/account-repository.js';
import { TransactionRepository } from '../../../src/infrastructure/repositories/transaction-repository.js';
import { WebsitesCostRepository } from '../../../src/infrastructure/repositories/websites-cost-repository.js';

describe('WebsitesModule',()=>{
 function createModule(){const storage=new InMemoryStorageAdapter();const keys=()=>storage.keys();const profileRepo=new IncomeProfileRepository(storage,'u1',keys);const clientRepo=new WebsitesClientRepository(storage,'u1',keys);const projectRepo=new WebsitesProjectRepository(storage,'u1',keys);const paymentRepo=new WebsitesPaymentRepository(storage,'u1',keys);const costRepo=new WebsitesCostRepository(storage,'u1',keys);const accountRepo=new AccountRepository(storage,'u1',keys);const txRepo=new TransactionRepository(storage,'u1',keys);const module=createWebsitesModule({websitesClientRepository:clientRepo,websitesProjectRepository:projectRepo,websitesPaymentRepository:paymentRepo,incomeProfileRepository:profileRepo,transactionRepository:txRepo,accountRepository:accountRepo,applicationTransaction:new ApplicationTransaction(storage)});return {module,profileRepo,accountRepo,txRepo,paymentRepo,costRepo};}
 async function seed(){const x=createModule();await x.profileRepo.save({id:'w1',userId:'u1',type:'websites',name:'Freelance',description:'',archived:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});return x;}
 it('creates clients and projects only inside an active websites profile',async()=>{const {module}=await seed();const client=await module.createClient({userId:'u1',incomeProfileId:'w1',name:'ACME'});const project=await module.createProject({userId:'u1',incomeProfileId:'w1',clientId:client.id,name:'Company Website',agreedValue:2500});assert.equal(project.clientId,client.id);assert.equal((await module.listProjects({userId:'u1',incomeProfileId:'w1'})).length,1);});
 it('rejects projects linked to a missing client',async()=>{const {module}=await seed();await assert.rejects(module.createProject({userId:'u1',incomeProfileId:'w1',clientId:'missing',name:'Broken'}),/NOT_FOUND/);});
 it('rejects archived profiles',async()=>{const {module,profileRepo}=await seed();const p=await profileRepo.findById('w1');p.archived=true;await profileRepo.save(p);await assert.rejects(module.createClient({userId:'u1',incomeProfileId:'w1',name:'ACME'}),/ARCHIVED_ENTITY/);});
 it('does not expose archived clients or projects',async()=>{const {module}=await seed();const c=await module.createClient({userId:'u1',incomeProfileId:'w1',name:'ACME'});const p=await module.createProject({userId:'u1',incomeProfileId:'w1',clientId:c.id,name:'Site'});await module.archiveClient({clientId:c.id});await module.archiveProject({projectId:p.id});assert.equal((await module.listClients({userId:'u1',incomeProfileId:'w1'})).length,0);assert.equal((await module.listProjects({userId:'u1',incomeProfileId:'w1'})).length,0);});
 it('creates exactly one ledger income transaction for a paid website payment',async()=>{const {module,accountRepo,txRepo}=await seed();await accountRepo.save({id:'a1',userId:'u1',name:'Bank',type:'bank',icon:'landmark',color:'#0000FF',archived:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});const client=await module.createClient({userId:'u1',incomeProfileId:'w1',name:'ACME'});const project=await module.createProject({userId:'u1',incomeProfileId:'w1',clientId:client.id,name:'Site'});const payment=await module.createPayment({userId:'u1',incomeProfileId:'w1',projectId:project.id,amount:1000,date:'2026-10-02',description:'Milestone',status:'paid',accountId:'a1'});assert.ok(payment.linkedTransactionId);const txs=await txRepo.loadAll();assert.equal(txs.length,1);assert.equal(txs[0].amount,1000);assert.equal(txs[0].metadata.websitesPaymentId,payment.id);});
 it('creates one expense transaction for a paid project cost',async()=>{const {module,accountRepo,txRepo}=await seed();await accountRepo.save({id:'a1',userId:'u1',name:'Bank',type:'bank',icon:'landmark',color:'#0000FF',archived:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});const client=await module.createClient({userId:'u1',incomeProfileId:'w1',name:'ACME'});const project=await module.createProject({userId:'u1',incomeProfileId:'w1',clientId:client.id,name:'Site'});const cost=await module.createCost({userId:'u1',incomeProfileId:'w1',projectId:project.id,amount:200,category:'hosting',date:'2026-10-02',description:'Hosting',status:'paid',accountId:'a1'});assert.ok(cost.linkedTransactionId);const txs=await txRepo.loadAll();assert.equal(txs.length,1);assert.equal(txs[0].type,'expense');assert.equal(txs[0].amount,200);});
 it('analytics separates projected revenue, realized cash and paid costs',async()=>{const {module,accountRepo}=await seed();await accountRepo.save({id:'a1',userId:'u1',name:'Bank',type:'bank',icon:'landmark',color:'#0000FF',archived:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});const client=await module.createClient({userId:'u1',incomeProfileId:'w1',name:'ACME'});const project=await module.createProject({userId:'u1',incomeProfileId:'w1',clientId:client.id,name:'Site'});await module.createPayment({userId:'u1',incomeProfileId:'w1',projectId:project.id,amount:1000,date:'2026-10-02',description:'Paid',status:'paid',accountId:'a1'});await module.createPayment({userId:'u1',incomeProfileId:'w1',projectId:project.id,amount:500,date:'2026-10-03',description:'Pending',status:'pending'});await module.createCost({userId:'u1',incomeProfileId:'w1',projectId:project.id,amount:200,category:'hosting',date:'2026-10-02',description:'Hosting',status:'paid',accountId:'a1'});const a=await module.getWebsitesAnalytics({userId:'u1',incomeProfileId:'w1'});assert.equal(a.totalRevenue,1500);assert.equal(a.realizedRevenue,1000);assert.equal(a.totalCost,200);assert.equal(a.realizedCost,200);assert.equal(a.totalNet,1300);});
});
